### ISSUE TITLE
FR: Private repo support

### ISSUE THREAD

**Issue by tyler36** [wei/socialify#105]
Wow ... those images looks so beautiful.

I have a few public repos but mostly work with private repos. The website isn't able to see them because they're ... private. 

I'd like to keep a consistent readme style across all project. Is there currently a process for private repos?

**Comment by CryogenicPlanet** [comment]
Hey

The best solution I see for this is to self host this repo yourself on vercel. Then you could authenticate yourself with a PAT and add that to the graphql requests which would allow you to create these images for private repos.

**Comment by tyler36** [comment]
Thank you for the update.

Would I be able to achieve the same thing hosting locally instead of vercel?

**Comment by CryogenicPlanet** [comment]
Yeah definitely! It will work on any deployment, I just recommend vercel as it is the easiest for nextjs projects. 

If you are deploying yourself, make sure you are running the nextjs server correctly. The docs are here https://nextjs.org/docs/deployment#other-hosting-options

**Comment by tyler36** [comment]
Thank you for the update.

I tried adding the dockerfile and running the command but I got a "Error: Cannot find module '/app/server.js'".  Im pretty new to docker so I might need to set aside some time to figure it out.

Thanks again!
