### ISSUE TITLE
`owner` query string not honored

### ISSUE THREAD

**Issue by wei** [wei/socialify#12]
Example: https://github-socialify.netlify.app/facebook/react?owner=1

`owner=1` but it's still unchecked and not being shown. If fact, it shows undefined when checked. 

Related to #11 and #6

**Comment by CryogenicPlanet** [comment]
Related issue when opening owner link
![image](https://user-images.githubusercontent.com/10355479/94366250-8e0a6c00-00f4-11eb-80ff-82aa348043af.png)
