### ISSUE TITLE
[BUG] Not updating issues open

### ISSUE THREAD

**Issue by KendallDoesCoding** [wei/socialify#123]
I created a test issue to test if socialify would update the issue number on the banner, it didn't update, it only updated when I took a link, got rid of something, then it updated and I waited for 10-12 mins, don't think it was supposed to be like that, I thought it auto updates?

![image](https://user-images.githubusercontent.com/84712013/160272718-2794d30d-e222-458a-906a-88346af32d43.png)
![image](https://user-images.githubusercontent.com/84712013/160272725-de503ebf-89d1-40d5-bcad-3f221902caed.png)

**Comment by KendallDoesCoding** [comment]
well it takes a few hours ig it worked now.

**Comment by CryogenicPlanet** [comment]
@KendallDoesCoding Check https://github.com/wei/socialify/issues/73 it should answer your question, the default is 1 hr, you can set it as low as 10 mins.

You can also self deploy this repo and set lower limits, as we don't want to exhaust our Github rate limit

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Check #73 it should answer your question, the default is 1 hr, you can set it as low as 10 mins.
> 
> You can also self deploy this repo and set lower limits, as we don't want to exhaust our Github rate limit

Hey Rahul, thanks a lot for this, how can I set it as low as 10 mins?

**Comment by CryogenicPlanet** [comment]
> > @KendallDoesCoding Check #73 it should answer your question, the default is 1 hr, you can set it as low as 10 mins.
> > 
> > You can also self deploy this repo and set lower limits, as we don't want to exhaust our Github rate limit
> 
> Hey Rahul, thanks a lot for this, how can I set it as low as 10 mins?
> 

Check this out https://github.com/wei/socialify/issues/73#issuecomment-720892188

**Comment by KendallDoesCoding** [comment]
> > > @KendallDoesCoding Check #73 it should answer your question, the default is 1 hr, you can set it as low as 10 mins.
> > > You can also self deploy this repo and set lower limits, as we don't want to exhaust our Github rate limit
> > 
> > 
> > Hey Rahul, thanks a lot for this, how can I set it as low as 10 mins?
> 
> Check this out [#73 (comment)](https://github.com/wei/socialify/issues/73#issuecomment-720892188)

Thanks a lot!
