### ISSUE TITLE
add Svelte icon

### ISSUE THREAD

**Issue by carlos-dubon** [wei/socialify#131]
I have a svelte project, but no icon is show.

https://github.com/carlos-dubon/svelte-cool-toast

**Comment by wei** [comment]
This is coming real soon! 

Click to try:

[![](https://socialify-git-simple-icons-whe.vercel.app/carlos-dubon/svelte-cool-toast/image?description=1&font=Bitter&language=1&name=1&owner=1&pattern=Circuit%20Board&stargazers=1&theme=Light)](https://socialify-git-simple-icons-whe.vercel.app/carlos-dubon/svelte-cool-toast?description=1&font=Bitter&language=1&name=1&owner=1&pattern=Circuit%20Board&stargazers=1&theme=Light)
