### ISSUE TITLE
Support new line in description

### ISSUE THREAD

**Issue by vLuckyyy** [wei/socialify#186]
Is it possible to make the text separate? doesn't want to combine the text from these two lines, and socialify does it automatically!

![image](https://user-images.githubusercontent.com/65517973/215167294-e59c2b21-e7c8-49c0-a0e7-11659538b196.png)
![image](https://user-images.githubusercontent.com/65517973/215167330-f16bdb4b-d3a7-43c8-a66b-0bac6aec0883.png)
It's just that "made with love and some cringe" is must lower than "Testing text"

**Comment by CryogenicPlanet** [comment]
Hey!

Happy to accept a PR for the same, we are rendering the description in this `<p>` tag here https://github.com/wei/socialify/blob/9d6b91d91e00d325dd07b8047b645045ba9905c4/src/components/preview/card.tsx#L134-L150

I think a `whitespace: pre-wrap` in the style should fix this

**Comment by vLuckyyy** [comment]
Thanks, I'll try to do a PR, thanks for your help!

**Comment by vLuckyyy** [comment]
Hi, I made these changes. But I can't quite adapt the unit test for it, would you like to help?

**Comment by CryogenicPlanet** [comment]
You have to make a PR can't help you with anything before that.

But for the tests you just need to update the snapshots

**Comment by wei** [comment]
Resolved in #210. Thank you!
