### ISSUE TITLE
How to directly output .png format

### ISSUE THREAD

**Issue by ElainaFanBoy** [wei/socialify#213]
.svg inconvenient a lot, sometimes

**Comment by wei** [comment]
Hello @ElainaFanBoy , you can replace `/image` with `/png` to use the experimental png endpoint. 

We opt to not use png by default to preserve bandwidth.

## e.g.
### svg
![socialify](https://socialify.git.ci/wei/socialify/image?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light)
`https://socialify.git.ci/wei/socialify/image?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light`

### png
![socialify](https://socialify.git.ci/wei/socialify/png?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light)
`https://socialify.git.ci/wei/socialify/png?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light`

**Comment by wei** [comment]
Looks like png endpoint only works once. Related to https://github.com/wei/socialify/issues/214

**Comment by ElainaFanBoy** [comment]
> Hello @ElainaFanBoy , you can replace `/image` with `/png` to use the experimental png endpoint.
> 
> We opt to not use png by default to preserve bandwidth.
> 
> ## e.g.
> ### svg
> ![socialify](https://camo.githubusercontent.com/b4eb314ef9504ebfaf2c4ec3f244397bddbab485cc9bce29148ed2506cabc6a0/68747470733a2f2f736f6369616c6966792e6769742e63692f7765692f736f6369616c6966792f696d6167653f6465736372697074696f6e3d3126666f6e743d52616c65776179266973737565733d31266c616e67756167653d31267061747465726e3d436861726c696525323042726f776e2670756c6c733d31267374617267617a6572733d31267468656d653d4c69676874) `https://socialify.git.ci/wei/socialify/image?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light`
> 
> ### png
> ![socialify](https://camo.githubusercontent.com/9278f154a4c1cd54d99b5084803ccbbc6ca4619b6ebb85ddb750e20b2fca5c73/68747470733a2f2f736f6369616c6966792e6769742e63692f7765692f736f6369616c6966792f706e673f6465736372697074696f6e3d3126666f6e743d52616c65776179266973737565733d31266c616e67756167653d31267061747465726e3d436861726c696525323042726f776e2670756c6c733d31267374617267617a6572733d31267468656d653d4c69676874) `https://socialify.git.ci/wei/socialify/png?description=1&font=Raleway&issues=1&language=1&pattern=Charlie%20Brown&pulls=1&stargazers=1&theme=Light`

Thank you very much
