### ISSUE TITLE
Is Socialify down?

### ISSUE THREAD

**Issue by Welding-Torch** [wei/socialify#216]
![image](https://github.com/wei/socialify/assets/46340124/2cc275b4-1c50-4521-ac73-79066992bc36)

A few days ago, my github repo with socialify was working just fine. Today, when I checked my repo, the link was broken. I had a look at Socialify's repository on GitHub and saw that all the examples here are broken too. Is Socialify down?

**Comment by Welding-Torch** [comment]
When I click the socialify link in my github, I get this error
`
{"error":"Unexpected token 'e', \"error code: 1016\" is not valid JSON","stack":"SyntaxError: Unexpected token 'e', \"error code: 1016\" is not valid JSON\n    at (vc/edge/function:69:44)\n    at (vc/edge/function:69:2614)\n    at (vc/edge/function:69:2764)\n    at (vc/edge/function:74:7968)"}
`

**Comment by GLGDLY** [comment]
Also have this problem, getting `Error Fetching Resource`

**Comment by Welding-Torch** [comment]
@wei

**Comment by wei** [comment]
Looking into it. Very weird only breaks on the production build. All PR builds are fine XD.

**Comment by wei** [comment]
For some reason the production deployment on Vercel starts to fail without any change from our end. 

https://socialify-git-master-github-socialify.vercel.app/wei/socialify/image?language=1&name=1&owner=1&stargazers=1&theme=Auto

[![](https://socialify-git-master-github-socialify.vercel.app/wei/socialify/image?language=1&name=1&owner=1&stargazers=1&theme=Auto)](https://socialify-git-master-github-socialify.vercel.app/wei/socialify/image?language=1&name=1&owner=1&stargazers=1&theme=Auto)

For now I have created a branch deployment from `master-alt` branch and assigned our main domain to it. It seems to be working fine now:

[![](https://socialify.git.ci/wei/socialify/image?language=1&name=1&owner=1&stargazers=1&theme=Auto)](https://socialify.git.ci/wei/socialify/image?language=1&name=1&owner=1&stargazers=1&theme=Auto)

Let's wait a few days and check back on the production deployment.

**Comment by Welding-Torch** [comment]
Hey, it's been a few days. The `master-alt` solution is working great. Has the reason for the fail in production that happened before been found?

**Comment by wei** [comment]
Hello, thanks for checking back on this. 

I have a ticket open with Vercel, still waiting to hear back. Will update here once I hear something!

**Comment by wei** [comment]
@Welding-Torch Vercel replied and says it was likely a transient issue. 

It is now functional and I've switched it back to -> master branch.
