### ISSUE TITLE
Allows adjusting image aspect ratio

### ISSUE THREAD

**Issue by hyoban** [wei/socialify#254]

**Comment by CryogenicPlanet** [comment]
Is the idea to have the images generated for purposes outside og images? As the og images have a fixed aspect ratio

**Comment by hyoban** [comment]
Yes, i want to use this in my blog as a GitHub card.

**Comment by CryogenicPlanet** [comment]
Interesting okay, happy to accept a PR for this and guide you, help with questions etc - that said I don't think this was really designed to have the aspect ratio changed all that much

the entry point to changing aspect ratio would be here https://github.com/wei/socialify/blob/3760dcc804f5677adb576440c3f4f5e5d58227b9/common/renderSVG.tsx#L22-L34

This file has a lot of mentions of the aspect ratio, but you will notice a lot of the styling in https://github.com/wei/socialify/blob/master/src/components/preview/card.tsx#L11 is sorta hardcoded for the standard width/height so would definitely need some design iteration too.

There is also a question about should it be responsive or a few fixed aspect ratios

If you are interested in taking this happy - happy to dedicate some more time to help with this and explain things etc

**Comment by hyoban** [comment]
I would love to make a PR for this issue. I think maybe we only need to change the height of card based on the inner content height. WDYT?

**Comment by wei** [comment]
@hyoban Could you explain more about your vision on how this will work? Perhaps a wireframe? 
Are you thinking about shifting the elements in the current layout or just expanding background to fill the space above and below?

**Comment by hyoban** [comment]
> just expanding background to fill the space above and below

Yes, something like this.

![image](https://github.com/wei/socialify/assets/38493346/60d516b4-6809-4513-b6f9-aaa1fdc34915)

**Comment by wei** [comment]
@hyoban Can you explain what the red box is? 

also do you propose adding aspect ratio as an input or dropdown on the UI and API? or allow users to specify width/height?

**Comment by hyoban** [comment]
The red box means this content is going to be removed. For example, excluding the description section will reduce the content height.

For me, I think dynamically deciding the card height based on the content is enough. But maybe allowing users to specify width/height is more flexible.

**Comment by wei** [comment]
Thanks for the suggestion, I am not yet convinced this is a flushed out use-case as is. Let's close as not planned for now. 

Feel free to open a new future request with a more thorough user story and we can get community votes on it.
