### ISSUE TITLE
Upgrade to Next.js 14 Best Practices

### ISSUE THREAD

**Issue by wei** [wei/socialify#272]
In addition to just bumping the version like in https://github.com/wei/socialify/pull/268, let's also update the [project structure](https://nextjs.org/docs/getting-started/project-structure) to the latest recommended by Next.js (App directory). Let's also explore the use of server components (if applicable).

**Comment by KemingHe** [comment]
Hello, @wei. Happy to assist you with migrating to using App dir. Good news is that NextJS supports both at the same time so we can do incremental moves. Let me know how you'd like to proceed. I'm very familiar with the process. 

Hear from you soon.

**Comment by wei** [comment]
> Hello, @wei. Happy to assist you with migrating to using App dir. Good news is that NextJS supports both at the same time so we can do incremental moves. Let me know how you'd like to proceed. I'm very familiar with the process. 
> 
> 
> 
> Hear from you soon.

Hey hey @KemingHe awesome! That'd bea lot of help ❤️. Assigning to you for now 😁

**Comment by wei** [comment]
Sure, I will merge dependabot's https://github.com/wei/socialify/pull/289 for the version bump since it's backwards compatible.

**Comment by wei** [comment]
Upgrade to Next.js 14 in https://github.com/wei/socialify/pull/289 has been complete. Pending research on whether App directory, server components, or any other Next 14 features make sense in our project.

**Comment by KemingHe** [comment]
Honestly, Page Router is fine for Next.js 14, I assume it will take at least 1~2 year until they sunset it. The upside App Router brings to the project are:

1. Eliminates manual routing, structure/flexibility tradeoff (though more beginner-friendly),
2. Centralized src, api, components code management, easier to refactor, especially with aliasing,

and that's about it. The client/server declaration can just be hard-coded into each page. 

All in all, if you want new features over slightly better and future-proofing code, I recommend shelving this util nearing Next ver 15 release.

Let me know what you think: @wei

**Comment by wei** [comment]
Thanks for the insight. Sounds like a plan.
