### ISSUE TITLE
Quality-of-life suggestion, happy to help

### ISSUE THREAD

**Issue by KemingHe** [wei/socialify#291]
Total number of ts(x) files: 46
Average local relative import of each file: ~3
Time managing each import: ~15 seconds

## Estimated time save **per dev per patch** 46*3*15/3600 = .575 hour

That's if they do it non-stop, only once.

@wei Hi, since I'm assigned issue #272, (incrementally) migrating from NextJS's `Page Rounter` to the ver 14 `App Router`, I also want to make my plus future dev's lives easier by refactoring import path from **relative** to **aliasing**, so that paths are modularized and easy to batch-mutate.

```typescript
// Before:
import type Configuration from '../../../common/types/configType'

// After:
import type Configuration from '@common/types/configType' 

// Only need to modify the `path` in `tsconfig.json` to update all uses of `@common`
```

This will positively impact us by having `good-first-issue' picked up and resolved more quickly.

Let me know if you are interested.

**Comment by wei** [comment]
Great! Sounds good to me.

**Comment by wei** [comment]
Great! you've convinced me. Please make a `@/` point to the root of the project `/` instead of only `@common` pointing to common folder.
