### ISSUE TITLE
Doc: Credit the contributors in package.json and README.md using Contrib.Rocks

### ISSUE THREAD

**Issue by KemingHe** [wei/socialify#407]
# Credit Our Contributors

Propose to add contributor info (name, email, url (LinkedIn maybe?)) in `package.json` and README.md. We can use [Contrib.Rocks](https://contrib.rocks) to dynamically generate a contributor GitHub profile listing, and auto-links to the repo contributors page. See below:

## Contrib.Rocks Site

https://contrib.rocks/preview?repo=wei%2Fsocialify

## Preview

<a href="https://github.com/wei/socialify/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=wei/socialify" />
</a>

Made with [contrib.rocks](https://contrib.rocks).

**Comment by wei** [comment]
Merged in as a part of #404. We'll opt for README.md for now, we can consider https://allcontributors.org in the future with more detailed contribution and ability to link to each members' profile.
