### ISSUE TITLE
Display error for long svg data uri

### ISSUE THREAD

**Issue by wei** [wei/socialify#419]
When user enters a SVG data uri that is more than 1,600 characters,
1. Add a warning or error (red border) around the SVG Logo input
2. Display a message "URI is too long, please use an SVG image URL instead."

_Originally posted by @wei in https://github.com/wei/socialify/issues/406#issuecomment-2536604810_

**Comment by slusy** [comment]
Hey, I would like to work on this

**Comment by slusy** [comment]
@wei Sure, I will do it

**Comment by slusy** [comment]
Hey @wei, when running the e2e tests it's generating new snapshots for Darwin. Should I include this as well in the PR?

**Comment by slusy** [comment]
Yeah, let me check it out
