### ISSUE TITLE
Add version on the footer and HTTP headers

### ISSUE THREAD

**Issue by wei** [wei/socialify#420]
- [x] Add version in the footer, e.g. _(v2.14.0)_
- [x] Add version as a meta tag in HTML
- [x] Add version in a new HTTP header of all responses, e.g. `X-SOCIALIFY-VERSION: v2.14.0`

Version should be pulled directly from `package.json`.

**Comment by KemingHe** [comment]
I can take on both, should be pretty simple. **Should I prioritize this or the NextJS 15 migration?**

**Comment by wei** [comment]
NextJS 15 is the most important atm.
