### ISSUE TITLE
Test(enhancement): for e2e tests, use `dotenv` or automated scripts to set GITHUB_TOKEN instead of manually asking from devs every session

### ISSUE THREAD

**Issue by KemingHe** [wei/socialify#422]
## Problem

`playwright.config.ts` now asks for GITHUB_TOKEN per dev session. This is inconvenient and the workaround is dangerous as devs will export their GitHub token at the beginning of every session.

```Typescript
// CI-friendly but not developer-friendly.
// TODO: Recommend using dotenv instead, plus, "next build && next start"
// already sets the environment variable if .env is present.
if (!process.env.GITHUB_TOKEN) {
  console.error('Please set GITHUB_TOKEN before running the tests')
  process.exit(1)
}
```

## Proposed Solution

Instead of in `playwright.config.ts`, we can add a check for `process.env.GITHUB_TOKEN` in the nextjs app, since that `next build && next start` already loads the .env if present.

**Comment by wei** [comment]
Good idea, thanks for the suggestion!

**Comment by KemingHe** [comment]
Great, will do very quickly after #423 . Then probly back to the NextJS 15 migration big task.
