### ISSUE TITLE
Remove unused npm packages

### ISSUE THREAD

**Issue by wei** [wei/socialify#434]
I noticed there are some unused packages, like `graphql`, `graphql-compiler`, perhaps `react-error-boundary`, and others. 

Let's go through and remove all the unused packages.

**Comment by Sunny-64** [comment]
Hi, I would like to work on this issue.

**Comment by wei** [comment]
Welcome @Sunny-64 , You got it!

**Comment by Sunny-64** [comment]
Thanks!! 😀
