### ISSUE TITLE
Feature Request: generate transparent background image

### ISSUE THREAD

**Issue by krau** [wei/socialify#439]
Supporting the download of PNG/WebP images with transparent backgrounds will offer users greater customization, enabling them to easily use their own created background images with the help of other image editing software.

**Comment by wei** [comment]
@krau great suggestion! Let's add a "Transparent" backgorund pattern. 

When selected, make the background transparent and show a chessboard pattern behind it to indicate it's transparent. Perhaps a light chessboard for Light mode and a dark chessboard for Dark mode.

Open to contributions.

**Comment by wei** [comment]
Thanks for the feature request, this is now deployed in version v2.15.0

![socialify](https://socialify.git.ci/wei/socialify/image?description=1&forks=1&issues=1&language=1&name=1&owner=1&pattern=Transparent&pulls=1&stargazers=1&theme=Auto)
