### ISSUE TITLE
Tracking Disclaimer

### ISSUE THREAD

**Issue by Korusuke** [wei/socialify#66]
Hey there!
First of all, great app!:fire:

I was just wondering that since the working and use of this would be similar to [shields.io](https://shields.io), it would be nice to add a "No Tracking" disclaimer.

Other options would be:

- Add a tracking feature and pass on that feature to the end-user.
- Keep tracking optional.

**Comment by wei** [comment]
## Tracking Policy
**Socialify** uses Google Analytics on web pages to understand overall usage. 
Generated image links do not have any tracking at this time.
