### ISSUE TITLE
Stars and Pulls don't update

### ISSUE THREAD

**Issue by pinpox** [wei/socialify#72]
Hello, 

I'm using the generated markdown at https://github.com/pinpox/nixos but the counters don't seem to update. 
For example the repository has one star at this time, but the image shows 2:
![image](https://user-images.githubusercontent.com/1719781/97816329-d2a99a00-1c94-11eb-8187-d173f93cb9cb.png)

If I create a new banner for the same repo the values are correct, but it doesn't seem to be tracking any changes otherwise

**Comment by CryogenicPlanet** [comment]
@pinpox All images are cached as to not overload the GitHub API rate limits, this caching is for about 4 hours at the moment. There is some discussion being had about reducing the cache, but rest assured the readme will automatically update in time. 

You can just look at our readme as an example, it isn't exactly correct(depends at the time of seing this) but it mostly keeps upto date.

Related #71

**Comment by pinpox** [comment]
Thanks for the quick response and sorry I didn't find the previous question. 4 hours is definitely fine with me.

**Comment by wei** [comment]
Updated default cache time to 1 hour in #74. You can overwrite it by adding `&cache=<seconds>` to the image url. 
However, this undocumented feature may be changed in the future. Thanks for your support!
