### ISSUE TITLE
Update all your repos at once

### ISSUE THREAD

**Issue by mheap** [wei/socialify#78]
👋 Evening @wei and @CryogenicPlanet 

I **love** the images produced by socialify and wanted to use them on all my repos, but didn't want to produce and upload them all one by one

So, I built a CLI that will do it for you. I hope it's ok to share it here with you. If you're interested, you can find it at https://github.com/mheap/github-social-image

**Comment by CryogenicPlanet** [comment]
This is awesome @mheap was definitely considering doing something like this myself but great to see you made it happen!
