### ISSUE TITLE
Add Kotlin logo

### ISSUE THREAD

**Issue by Mr-Skully** [wei/socialify#85]
Add Kotlin to the list of supported programming languages.

**Comment by CryogenicPlanet** [comment]
Hey, that's a great idea.

Feel free to make a PR here with the kotlin icon from devicons. 

Once the PR is merged, the images should automatically update with the kotlin logo after the cache expires! 

https://github.com/wei/socialify/blob/314b69daa296fba14381797eb92573c7369651d2/common/helpers.ts#L14-L36

**Comment by Mr-Skully** [comment]
Sure!
While I'm at it, can I also add some other popular languages like Haskell and Bash?

**Comment by wei** [comment]
This is coming real soon! 

Click to try:

[![](https://socialify-git-simple-icons-whe.vercel.app/Mr-Skully/kotlin-quick-guide/image?description=1&font=Raleway&owner=1&language=1&pattern=Floating%20Cogs&theme=Light)](https://socialify-git-simple-icons-whe.vercel.app/Mr-Skully/kotlin-quick-guide?description=1&font=Raleway&owner=1&language=1&pattern=Floating%20Cogs&theme=Light)
